# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

schedules:
- cron: 0 6 * * 1,2,3,4,5
  branches:
    include:
    - refs/heads/master
  always: true



pool:
  name: IDM


#######################################################################################
#             Basic Variables (should be changed)                                     #
#######################################################################################
variables:
  ENVIRONMENT:        'DEV02'

steps:
- task: Maven@3
  displayName: 'Compile and Validate solution Configuration test'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: 'clean validate compile'
    publishJUnitResults: false
    effectivePomSkip: true

- task: Maven@3
  displayName: 'Test cap EDS'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=capeds'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()



- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()

- task: Maven@3
  displayName: 'Test captogem'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=captogem'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()


- task: Maven@3
  displayName: 'Test JZ '
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=jz'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()


- task: Maven@3
  displayName: 'Test IDBANTWERP'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=idbanr'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()


- task: Maven@3
  displayName: 'Test IDBDUBLIN'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=idbdub'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed() 
  

- task: Maven@3
  displayName: 'Test IDBFRANKFURT'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=idbfrf'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed() 


- task: Maven@3
  displayName: 'Test ACBSNOT'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=acbsnot'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed() 


- task: Maven@3
  displayName: 'Test ACBSRP'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=acbsrp'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed() 


- task: Maven@3
  displayName: 'Test ACBSWR'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=acbswr'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed() 


- task: Maven@3
  displayName: 'Test CORPNLCC'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=corpnlcc'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()
  
- task: Maven@3
  displayName: 'Test CORPNLTCF'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=corpnltcf'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()
  
- task: Maven@3
  displayName: 'Test AGDESK'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=agdesk'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()  
  
- task: Maven@3
  displayName: 'Test AMSSEC'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=amssec'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()   

- task: Maven@3
  displayName: 'Test CASHMAN'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=cashman'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()

- task: Maven@3
  displayName: 'Test LOANSOI'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=loansoi'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()

- task: Maven@3
  displayName: 'Test TCFOLD'
  inputs:
    mavenPomFile: 'test-fnp8-config/pom.xml'
    goals: test
    options: '-Dfilenet.test.environment=$(ENVIRONMENT) -Dfilenet.test.objectstore=libra -Dtest=VerifySolutionConfigurationTest -Dfilenet.test.application=tcfold'
    testResultsFiles: '**/TEST-*.xml'
    jdkVersionOption: 1.8
  condition: succeededOrFailed()

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()

- task: mspremier.CreateWorkItem.CreateWorkItem-task.CreateWorkItem@1
  displayName: 'Create work item'
  inputs:
    teamProject: IDM
    workItemType: Task
    title: 'Verify solution - Libra Test cases are failing'
    areaPath: 'IDM\Implementation Squad'
    iterationPath: 'Implementation Squad@currentIteration'
    fieldMappings: 'System.Tags=''Libra Failed test cases'''
    associate: '$(Parameters.associate)'
    linkWorkItems: true
    linkType: 'System.LinkTypes.Hierarchy-Reverse'
    linkTarget: wiql
    targetWiql: '[System.Title] CONTAINS WORDS ''Unplanned Work'' AND [System.IterationPath] = @currentIteration(''[IDM]\Implementation Squad'')  AND [System.AreaPath] = ''IDM\Implementation Squad'''
    preventDuplicates: true
    keyFields: |
     System.AreaPath
     System.IterationPath
     System.Title
     
  condition: failed()
trigger: none